<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CDSLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>afc15667-dcd3-40a0-b606-f24660a87bdb</testSuiteGuid>
   <testCaseLink>
      <guid>12c791e5-cf98-4823-957f-416f047b5847</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Paywell/Login/PositiveTests/Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>191fb52a-c840-4a02-b5f6-831718594c9a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/xlsx</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>715595d0-828b-4207-83e0-95bcc9354607</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f9f1bd8-51ae-4617-b798-ff3eb404e332</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
